blog/urls.py
from django.urls import path, re_path
from blog import views

app_name = 'blog'
urlpatterns = [

    path('', views.PostLV.as_view(), name='index'),

    path('post/', views.PostLV.as_view(), name='post_list'),

    re_path(r'^post/(?P<slug>[-\w]+)/$', views.PostDV.as_view(), name='post_detail'),

    path('archive/', views.PostAV.as_view(), name='post_archive'),

    path('archive/<int:year>/', views.PostYAV.as_view(), name='post_year_archive'),

    path('archive/<int:year>/<str:month>/', views.PostMAV.as_view(), name='post_month_archive'),

    path('archive/<int:year>/<str:month>/<int:day>/', views.PostDAV.as_view(), name='post_day_archive'),

    path('archive/today/', views.PostTAV.as_view(), name='post_today_archive'),

    path('tag/', views.TagCloudTV.as_view(), name= 'tag_cloud'),

    path('tag/<str:tag>/', views.TaggedObjectLV.as_view(), name='tagged_object_list'),

    path('search/', views.SearchFormView.as_view(), name= 'search'),

    path('add/',
         views.PostCreateView.as_view(), name="add"),

    path('change/',
         views.PostChangeLV.as_view(), name="change"),

    path('<int:pk>/update/',
         views.PostUpdateView.as_view(), name="update"),

    path('<int:pk>/delete/',
         views.PostDeleteView.as_view(), name='delete'),
]

bookmark/urls.py
from django.urls import path
# from bookmark.views import BookmarkLV, BookmarkDV
from bookmark import views

app_name = 'bookmark'
urlpatterns = [
    path('', views.BookmarkLV.as_view(), name='index'),
    path('<int:pk>/', views.BookmarkDV.as_view(), name='detail'),

    path('add/',
         views.BookmarkCreateView.as_view(), name="add"
         ),

    path('change/',
         views.BookmarkChangeLV.as_view(), name="change",
         ),

    path('<int:pk>/update/',
         views.BookmarkUpdateView.as_view(), name="update",
         ),

    path('<int:pk>/delete/',
         views.BookmarkDeleteView.as_view(), name="delete",
         ),
]

mysite/urls.py
from django.conf.urls import include, url
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from mysite.views import HomeView
from mysite.views import UserCreateView, UserCreateDoneTV

# from bookmark.views import BookmarkLV, BookmarkDV

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/register/', UserCreateView.as_view(), name='register'),
    path('accounts/register/done/', UserCreateDoneTV.as_view(), name='register_done'),

    path('', HomeView.as_view(), name='home'),
    path('bookmark/', include('bookmark.urls')),
    path('blog/', include('blog.urls')),
    path('photo/', include('photo.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bookmark/models.py
from django.db import models
from django.contrib.auth.models import User

class Bookmark(models.Model):
    title = models.CharField('TITLE', max_length=100, blank=True,)
    url = models.URLField('URL', unique=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)

    def __str__(self):
        return self.title

bookmark/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView
from mysite.views import OwnerOnlyMixin

from bookmark.models import Bookmark
from django.views.generic import CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
# Create your views here.
class BookmarkLV(ListView):
    model= Bookmark

class BookmarkDV(DetailView):
    model= Bookmark

class BookmarkCreateView(LoginRequiredMixin, CreateView):
    model = Bookmark
    fields = ['title', 'url']
    success_url = reverse_lazy('bookmark:index')

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super().form_valid(form)


class BookmarkChangeLV(LoginRequiredMixin, ListView):
    template_name = 'bookmark/bookmark_change_list.html'

    def get_queryset(self):
        return Bookmark.objects.filter(owner=self.request.user)


class BookmarkUpdateView(OwnerOnlyMixin, UpdateView):
    model = Bookmark
    fields = ['title', 'url']
    success_url = reverse_lazy('bookmark:index')


class BookmarkDeleteView(OwnerOnlyMixin, DeleteView):
    model = Bookmark
    success_url = reverse_lazy('bookmark:index')

bookmark/templates/bookmark/bookmark_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Django Bookmark Detail</title>
</head>
<body>

<div id= "content">
    <h1> {{object.title}} </h1>
    <ul>
        <li>URL: <a href ="{{object.url}}"> {{object.url}}</a></li>
    </ul>
</div>
</body>
</html>

bookmark/templates/bookmark/bookmark_list.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Django Bookmark List {% endblock %}

{% block header %}
  <header class="masthead" style="background-image: url({% static 'img/home-bg.jpg'%})">
    <div class="overlay"></div>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <div class="site-heading">
            <h1> 북마크 페이지 </h1>
            <span class="subheading"> 북마크 리스트 입니다 </span>
          </div>
        </div>
      </div>
    </div>
  </header>
{% endblock %}

{% block content %}
<div id = "content">
    <h1>Bookmark List</h1>

    <ul>
        {% for bookmark in object_list %}
            <li><a href="{% url 'bookmark:detail' bookmark.id %}">{{ bookmark }}</a></li>
        {% endfor %}
    </ul>
</div>
{% endblock %}

{% block extra-script %}{% endblock %}